server:
  port: 8001
  servlet:
    context-path: /eureka/consumer

spring:
  application:
    name: eureka-consumer
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/


