server:
  port: 8080

spring:
  application:
    name: turbine

management:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

turbine:
  #参数指定了需要收集监控信息的服务名
  app-config: eureka-consumer
  aggregator:
    cluster-config: eureka-consumer
  #参数指定了集群名称为 default
  cluster-name-expression: metadata['cluster']
  combine-host-port: true
  #instanceUrlSuffix: eureka/consumer/actuator/hystrix.stream
  instanceUrlSuffix:
    eureka-consumer: eureka/consumer/actuator/hystrix.stream

